version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: proto-dev-mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=proto
    restart: always
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:7
    container_name: proto-dev-redis
    ports:
      - "6380:6379"
    restart: always
    volumes:
      - ./data/redis:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: proto-dev-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=proto-docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo=/usr/local/els-snapshots
      - action.destructive_requires_name=false
    ports:
      - 9201:9200
      - 9301:9300
    restart: always
    volumes:
      - ./els-snapshots:/usr/local/els-snapshots

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: proto-dev-kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://proto-dev-elasticsearch:9200
    links:
      - elasticsearch
